const API_URL = "http://127.0.0.1:8000/api/vehicles/";
const vehiclesData = [
  {
    id: 1,
    name: "Xiaomi YU7",
    type: "ev",
    image: "/image/xiaomi-YU7.JPG",
    price: 70,
    badge: { icon: "fas fa-bolt", label: "EV" },
  },
  {
    id: 2,
    name: "Audi RS7",
    type: "fuel",
    image: "/image/Audi-RS7.jpg",
    price: 180,
    badge: { icon: "fas fa-gas-pump", label: "Fuel" },
  },
  {
    id: 3,
    name: "Aprilia RSV4",
    type: "bike",
    image: "/image/aprilia-rsv4.jpg",
    price: 140,
    badge: { icon: "fas fa-motorcycle", label: "Bike" },
  },
  {
    id: 4,
    name: "BMW M4 AMG GT2",
    type: "fuel",
    image: "/image/bmw-m4-amg-gt2.jpg",
    price: 220,
    badge: { icon: "fas fa-gas-pump", label: "Fuel" },
  },
  {
    id: 5,
    name: "BMW M1000RR",
    type: "bike",
    image: "/image/bmw-M1000rr.webp",
    price: 180,
    badge: { icon: "fas fa-motorcycle", label: "Bike" },
  },
  {
    id: 6,
    name: "Tesla Model 3",
    type: "ev",
    image: "/image/Tesla-Model3.webp",
    price: 75,
    badge: { icon: "fas fa-bolt", label: "EV" },
  },
  {
    id: 7,
    name: "BMW S1000RR",
    type: "bike",
    image: "/image/bmw-s1000rr.avif",
    price: 150,
    badge: { icon: "fas fa-motorcycle", label: "Bike" },
  },
  {
    id: 8,
    name: "Xiaomi SU7",
    type: "ev",
    image: "/image/xiaomi-su7.jpg",
    price: 90,
    badge: { icon: "fas fa-bolt", label: "EV" },
  },
  {
    id: 9,
    name: "BMW M4",
    type: "fuel",
    image: "/image/bmw-m4.webp",
    price: 160,
    badge: { icon: "fas fa-gas-pump", label: "Fuel" },
  },
  {
    id: 10,
    name: "Audi EV",
    type: "ev",
    image: "/image/Audi-ev.avif",
    price: 80,
    badge: { icon: "fas fa-bolt", label: "EV" },
  },
  {
    id: 11,
    name: "Ducati Panigale V4",
    type: "bike",
    image: "/image/ducati-panigale-v4.jpg",
    price: 170,
    badge: { icon: "fas fa-motorcycle", label: "Bike" },
  },
  {
    id: 12,
    name: "Ducati V4 Turisho",
    type: "bike",
    image: "/image/Ducati-V4-Turisho.webp",
    price: 160,
    badge: { icon: "fas fa-motorcycle", label: "Bike" },
  },
  {
    id: 13,
    name: "BMW X5",
    type: "fuel",
    image: "/image/BMW-X5.avif",
    price: 140,
    badge: { icon: "fas fa-gas-pump", label: "Fuel" },
  },
  {
    id: 14,
    name: "Bugatti Chiron",
    type: "fuel",
    image: "/image/bugatti-chiron.avif",
    price: 900,
    badge: { icon: "fas fa-gas-pump", label: "Fuel" },
  },
  {
    id: 15,
    name: "Lexus RZ",
    type: "ev",
    image: "/image/Lexus-RZ.jpg",
    price: 90,
    badge: { icon: "fas fa-bolt", label: "EV" },
  },
  {
    id: 16,
    name: "Honda CBR1000RR",
    type: "bike",
    image: "/image/honda-cbr1000rr.jpg",
    price: 130,
    badge: { icon: "fas fa-motorcycle", label: "Bike" },
  },
  {
    id: 17,
    name: "BYD Sealion 7",
    type: "ev",
    image: "/image/byd-sealion7.webp",
    price: 65,
    badge: { icon: "fas fa-bolt", label: "EV" },
  },
  {
    id: 18,
    name: "Lamborghini Huracan",
    type: "fuel",
    image: "/image/Lamborghini-Huracan.webp",
    price: 500,
    badge: { icon: "fas fa-gas-pump", label: "Fuel" },
  },
  {
    id: 19,
    name: "Kawasaki Ninja H2R",
    type: "bike",
    image: "/image/kawasaki-ninja-h2r.jpg",
    price: 350,
    badge: { icon: "fas fa-motorcycle", label: "Bike" },
  },
  {
    id: 20,
    name: "Tesla Model S",
    type: "ev",
    image: "/image/Tesla-ModelS.webp",
    price: 130,
    badge: { icon: "fas fa-bolt", label: "EV" },
  },
  {
    id: 21,
    name: "Range Rover Defender",
    type: "fuel",
    image: "/image/Range-Rover-defender.webp",
    price: 220,
    badge: { icon: "fas fa-gas-pump", label: "Fuel" },
  },
  {
    id: 22,
    name: "Mercedes C300",
    type: "fuel",
    image: "/image/Mercedes-C300.webp",
    price: 110,
    badge: { icon: "fas fa-gas-pump", label: "Fuel" },
  },
  {
    id: 23,
    name: "BYD Yangwang U9",
    type: "ev",
    image: "/image/BYD-YangwangU9.webp",
    price: 250,
    badge: { icon: "fas fa-bolt", label: "EV" },
  },
  {
    id: 24,
    name: "Suzuki GSX-R1000",
    type: "bike",
    image: "/image/Suzuki-GSX-R1000.jpg",
    price: 120,
    badge: { icon: "fas fa-motorcycle", label: "Bike" },
  },
  {
    id: 25,
    name: "Porsche 911",
    type: "fuel",
    image: "/image/porsche-911.webp",
    price: 350,
    badge: { icon: "fas fa-gas-pump", label: "Fuel" },
  },
  {
    id: 26,
    name: "Mazda EZ-6",
    type: "ev",
    image: "/image/mazda-EZ66.jpg",
    price: 160, // Fixed: Changed from 17560 to 160
    badge: { icon: "fas fa-bolt", label: "EV" },
  },
  {
    id: 27,
    name: "Ferrari F8 Tributo",
    type: "fuel",
    image: "/image/Ferrari-F8-Tributo.jpeg",
    price: 600,
    badge: { icon: "fas fa-gas-pump", label: "Fuel" },
  },
  {
    id: 28,
    name: "Ford Mustang GT",
    type: "fuel",
    image: "/image/Ford-Mustang-GT.webp",
    price: 180,
    badge: { icon: "fas fa-gas-pump", label: "Fuel" },
  },
  {
    id: 29,
    name: "Yamaha R6",
    type: "bike",
    image: "/image/yamaha-r6.webp",
    price: 110,
    badge: { icon: "fas fa-motorcycle", label: "Bike" },
  },
  {
    id: 30,
    name: "Ford Mustang",
    type: "fuel",
    image: "/image/Ford-Mustang.avif",
    price: 150,
    badge: { icon: "fas fa-gas-pump", label: "Fuel" },
  },
  {
    id: 31,
    name: "Yamaha R1M",
    type: "bike",
    image: "/image/yamaha-r1m.jpg",
    price: 160,
    badge: { icon: "fas fa-motorcycle", label: "Bike" },
  },
];
export default vehiclesData;